"""Generate immutable Rust data from the canonical Python definitions.

Run from the directory containing splendor_v1:
    python -m splendor_v1.rust_engine_v2.generate_tables
No hand-maintained second copy of card data or payment IDs is required.
"""
from pathlib import Path

from splendor_v1.env.core import action_constants as actions
from splendor_v1.env.core.cost_lookup_table_v3 import (
    T1_PAYMENT_LOOKUP, T2_PAYMENT_LOOKUP, T3_PAYMENT_LOOKUP,
)
from splendor_v1.env.core.enums import GemColor
from splendor_v1.env.data.data import BASE_TIER_1, BASE_TIER_2, BASE_TIER_3, NOBLES


def render_tables():
    colors = list(GemColor)[:5]
    cards = sorted(BASE_TIER_1 + BASE_TIER_2 + BASE_TIER_3, key=lambda c: c.id)
    nobles = sorted(NOBLES, key=lambda n: n.id)
    assert [c.id for c in cards] == list(range(90))
    assert [n.id for n in nobles] == list(range(10))
    lines = ["// Generated by generate_tables.py; do not edit by hand.",
             "use crate::engine::{Card, Noble};", ""]
    for name in ("ACTION_SPACE_SIZE", "BUY_T1_START", "BUY_T2_START", "BUY_T3_START",
                 "BUY_RESERVED_START", "DISCARD_START", "NOBLE_START"):
        lines.append(f"pub const {name}: usize = {getattr(actions, name)};")
    lines.append("pub const CARDS: [Card; 90] = [")
    for c in cards:
        cost = [c.cost.get(color, 0) for color in colors]
        mapping = sorted(range(5), key=lambda i: (-cost[i], i))
        lines.append(f"    Card {{ tier: {c.tier}, points: {c.points}, bonus: {c.bonus_color.value}, cost: {cost}, mapping: {mapping} }},")
    lines.extend(["];", "pub const NOBLES: [Noble; 10] = ["])
    for n in nobles:
        req = [n.requirement.get(color, 0) for color in colors]
        lines.append(f"    Noble {{ points: {n.points}, requirement: {req} }},")
    lines.append("];")
    for tier, table in enumerate((T1_PAYMENT_LOOKUP, T2_PAYMENT_LOOKUP, T3_PAYMENT_LOOKUP), 1):
        lines.append(f"pub const PAYMENTS_{tier}: [[u8; 5]; {len(table)}] = [")
        lines.extend(f"    {list(payment)}," for payment in table)
        lines.append("];")
    lines.append("pub const GEM_ACTIONS: [&[usize]; 30] = [")
    lines.extend("    &[" + ", ".join(str(c.value) for c in combo) + "]," for combo in actions.GEM_ACTIONS)
    lines.append("];")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    target = Path(__file__).parent / "src" / "tables.rs"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_tables(), encoding="utf-8")
    print(f"Generated {target}")
